ASSET_T {
  ASSET_ID: "0000000656780"
  UPDT_TMSTMP: "2014-07-11-11.43.24.196686"
  ADD_AGCY: "N"
  AD_CD_PREV1: "0"
  AD_CD_PREV2: "0"
  APRVL_DT: "20140711"
  ASSET_CBND_FLG: "N"
  ASSET_ID_TYP: "F"
  ASSET_THRLD_FLG: "Y"
  ASSET_TYP: "JU"
  ASSET_VAL: "+000013888939.00"
  ASSET_VAL_AT_SZ: "+000000000000.00"
  DMGE_PRESNT_FLG: "N"
  ET_FLG: "N"
  EXPED_NOT_SVD: "N"
  EXP_INCUR: "N"
  FIRE_BEGN_DT: "20121121"
  FIRE_TYP: "I"
  FM_PREP_DT: "20140711"
  FO_TYP: "D"
  GOV_PRIVT_CD: "G"
  INTRA_AGCY_ASST: "N"
  LIEN_EXISTS: "N"
  OCDETF_CA_FLG: "N"
  OFC_ID: "3220"
  PARA_PROC_FLG: "N"
  PROC_DIST: "MIE"
  PTY_EXISTS_FLG: "Y"
  QK_RLS_IND: "N"
  SHR_PRESNT_FLG: "N"
  STAT_PRIM: "D52"
  STAT_VIOL_CD: "D94"
  SZ_AGCY_CD: "FBI"
  SZ_DIST: "MIE"
  SZ_FM_ENT_DT: "20140711"
  SZ_METH: "O"
  SZD_FRM_BUSFLG: "N"
  VCTMS_ANTCPTD_F: "N"
  CA_ENT_DT: "20110909"
  INTL_SHR_FLG: "N"
  PGM_YR: "2013"
  ASSET_VAL_FIRE: "+000013888939.00"
  RSTN_ANT_FLG: "N"
  AD_CD_DEA_2035: "0"
  CMPLX_ASSET_FLG: "N"
}
ASSET_T {
  ASSET_ID: "0000000665060"
  UPDT_TMSTMP: "2001-12-08-06.00.00.000000"
  ADD_AGCY: "Y"
  AD_CD_PREV1: "0"
  AD_CD_PREV2: "0"
  APRSD_DT: "19970312"
  APRVL_DT: "19950517"
  ASSET_CBND_FLG: "N"
  ASSET_DSPN_DT: "19970312"
  ASSET_ID_TYP: "S"
  ASSET_PUB_DT: "19951231"
  ASSET_SUBTYP: "02"
  ASSET_THRLD_FLG: "Y"
  ASSET_TYP: "FI"
  ASSET_VAL: "+000000135671.45"
  ASSET_VAL_AT_SZ: "+000000100000.00"
  CRMNL_INDCT_DT: "19950419"
  CTRY_CD: "USA"
  DMGE_PRESNT_FLG: "N"
  ET_FLG: "N"
  EXPED_NOT_SVD: "N"
  EXP_INCUR: "N"
  FM_PREP_DT: "19950517"
  FO_TYP: "D"
  GOV_PRIVT_CD: "G"
  INTRA_AGCY_ASST: "N"
  LIEN_EXISTS: "N"
  OCDETF_CA_FLG: "Y"
  OFC_ID: "3390"
  PROC_DIST: "ARE"
  PTY_EXISTS_FLG: "Y"
  QK_RLS_IND: "N"
  SHR_PRESNT_FLG: "Y"
  STAT_PRIM: "F06"
  STAT_VIOL_CD: "B89"
  SZ_AGCY_CD: "FBI"
  SZ_DIST: "ARE"
  SZ_DT: "19970122"
  SZ_FM_ENT_DT: "19950524"
  SZ_METH: "B"
  SZ_DT_JUD: "19970122"
  SZ_JUD_SUB_OFC: "00"
  SZ_ST: "AR"
  SZD_FRM_BUSFLG: "N"
  VCTMS_ANTCPTD_F: "N"
  PGM_YR: "1997"
  RSTN_ANT_FLG: "N"
  AD_CD_DEA_2035: "0"
  CMPLX_ASSET_FLG: "N"
}
DAG71_T {
  ASSET_ID: "0000000010077"
  OAG_NCIC_CD: "DCUSC5000"
  UPDT_TMSTMP: "2000-01-05-16.06.47.114000"
  APRVL_DT: "19991104"
  FORGN_ASSET_FLG: "N"
  SHR_ASST_FLG: "Y"
  SHR_CONTRIB_HRS: "1766"
  SHR_EXEC_DT: "20040217"
  SHR_EXEC_STS_CD: "EX"
  SHR_FED_AMT: "+000000000000.00"
  SHR_IA_EXP: "+000000001975.00"
  SHR_INFO_ORIGR: "N"
  SHR_OTH_ASSET: "Y"
  SHR_OTSDNG_LIEN: "+000000000000.00"
  SHR_PCT_TO_SHR: "+0000000020.0000"
  SHR_REQ_DT: "19991104"
  SHR_REQ_PCT: "+0000000026.6000"
  SHR_REQ_RECV_DT: "19991129"
  SHR_REQ_TYP: "C"
  SHR_ST_SZ_ASSET: "N"
  SHR_TL_INCM: "+000000009200.00"
  SHR_TYP: "J"
  SHR_USA_EXP: "+000000000000.00"
  SHR_USE_EQUIP: "N"
  SHR_USE_OFCL: "N"
  SHR_USE_OTHER: "Y"
  SHR_USE_SAL: "N"
  SHR_USE_VEHCL: "N"
  SHR_USMS_EXP: "+000000001258.60"
  SHR_XTRORD_EXP: "N"
  SOC_CD: "4402"
  SHR_USMS_LIEN_EXP: "+000000000000.00"
  SHR_EXEC_AMT: "+000000001193.28"
  FUNDS_LOC_CD: "TFF"
  OFFST_AMT: "+000000000000.00"
  BUDGT_ADJ_PCT: "+00000000000.000"
  BUDGT_ADJ_VAL: "+000000000000.00"
}
DAG71_T {
  ASSET_ID: "0000000000001"
  OAG_NCIC_CD: "MDDOAHY00"
  UPDT_TMSTMP: "2000-10-04-10.12.10.591000"
  APRVL_DT: "20000811"
  FORGN_ASSET_FLG: "N"
  LGL_CSL_CERT_DT: "20000811"
  LGL_CSL_ST: "DC"
  SHR_ASST_FLG: "Y"
  SHR_CONTRIB_HRS: "377"
  SHR_EXEC_DT: "20000929"
  SHR_EXEC_STS_CD: "SO"
  SHR_FED_AMT: "+000000000000.00"
  SHR_IA_EXP: "+000000000000.00"
  SHR_INFO_ORIGR: "Y"
  SHR_OTH_ASSET: "N"
  SHR_OTSDNG_LIEN: "+000000000000.00"
  SHR_PCT_TO_SHR: "+0000000000.0000"
  SHR_REQ_DT: "20000927"
  SHR_REQ_PCT: "+0000000100.0000"
  SHR_REQ_RECV_DT: "20000927"
  SHR_REQ_TYP: "C"
  SHR_ST_SZ_ASSET: "N"
  SHR_TL_INCM: "+000000000000.00"
  SHR_TYP: "J"
  SHR_USA_EXP: "+000000000000.00"
  SHR_USE_EQUIP: "N"
  SHR_USE_OFCL: "N"
  SHR_USE_OTHER: "Y"
  SHR_USE_SAL: "N"
  SHR_USE_VEHCL: "N"
  SHR_USMS_EXP: "+000000000000.00"
  SHR_XTRORD_EXP: "N"
  SHR_USMS_LIEN_EXP: "+000000000000.00"
  SHR_EXEC_AMT: "+000000000000.00"
  FUNDS_LOC_CD: "AFF"
  OFFST_AMT: "+000000000000.00"
  BUDGT_ADJ_PCT: "+00000000000.000"
  BUDGT_ADJ_VAL: "+000000000000.00"
}
