asset {
  asset_id: 656780
  update_timestamp: "2014-07-11-11.43.24.196686"
  additional_agencies_flag: false
  advertisement_code_prev1: 0
  advertisement_code_prev2: 0
  approval_date: "20140711"
  combined_asset_flag: false
  asset_id_type: "F"
  value_threshold_flag: true
  asset_type: "JU"
  asset_value: 1.3888939E7
  asset_value_at_seizure: 0.0
  damages_present_at_seizure: false
  sad_electronic_transfer_flag: false
  expedited_release_notice_served: false
  expenses_incurred_flag: false
  fire_begin_date: "20121121"
  fire_type: "I"
  form_preparation_date: "20140711"
  forfeiture_type: "D"
  government_private_code: "G"
  intra_agency_assistance_flag: false
  lien_exists_flag: false
  organized_crime_case_flag: false
  office_id: "3220"
  parallel_processing_flag: false
  processing_district: "MIE"
  party_exists_flag: true
  quick_release_flag: false
  sharing_present_flag: false
  primary_statute_code: "D52"
  statute_violation_code: "D94"
  seizing_agency_code: "FBI"
  seizure_district: "MIE"
  seizure_form_entry_date: "20140711"
  seizure_method_code: "O"
  seized_from_business_flag: false
  victims_anticipated_flag: false
  case_entered_date: "20110909"
  international_sharing_flag: false
  fbi_icc_program_year: "2013"
  asset_value_at_fire_begin: 1.3888939E7
  restitution_anticipated_flag: false
  dea_20_35_day_ad_code: "0"
  complex_asset_flag: false
}
asset {
  asset_id: 665060
  update_timestamp: "2001-12-08-06.00.00.000000"
  additional_agencies_flag: true
  advertisement_code_prev1: 0
  advertisement_code_prev2: 0
  appraisal_date: "19970312"
  approval_date: "19950517"
  combined_asset_flag: false
  disposal_date: "19970312"
  asset_id_type: "S"
  advertisement_publication_date: "19951231"
  asset_subtype_code: "2"
  value_threshold_flag: true
  asset_type: "FI"
  asset_value: 135671.45
  asset_value_at_seizure: 100000.0
  criminal_indictment_date: "19950419"
  country_code: "USA"
  damages_present_at_seizure: false
  sad_electronic_transfer_flag: false
  expedited_release_notice_served: false
  expenses_incurred_flag: false
  form_preparation_date: "19950517"
  forfeiture_type: "D"
  government_private_code: "G"
  intra_agency_assistance_flag: false
  lien_exists_flag: false
  organized_crime_case_flag: true
  office_id: "3390"
  processing_district: "ARE"
  party_exists_flag: true
  quick_release_flag: false
  sharing_present_flag: true
  primary_statute_code: "F06"
  statute_violation_code: "B89"
  seizing_agency_code: "FBI"
  seizure_district: "ARE"
  seizure_date: "19970122"
  seizure_form_entry_date: "19950524"
  seizure_method_code: "B"
  judicial_seizure_date: "19970122"
  seizing_judicial_sub_office: "0"
  seizure_state: "AR"
  seized_from_business_flag: false
  victims_anticipated_flag: false
  fbi_icc_program_year: "1997"
  restitution_anticipated_flag: false
  dea_20_35_day_ad_code: "0"
  complex_asset_flag: false
}
equitable_sharing {
  asset_id: 10077
  other_agency_ncic_code: "DCUSC5000"
  update_timestamp: "2000-01-05-16.06.47.114000"
  approval_date: "19991104"
  foreign_asset_flag: false
  unique_assistance_flag: true
  contributed_hours: 1766
  sharing_execution_date: "20040217"
  sharing_execution_status_code: "EX"
  federal_sharing_amount: 0.0
  investigative_agency_expense: 1975.0
  information_origin_flag: false
  other_assets_flag: true
  outstanding_lien_amount: 0.0
  percent_to_share: 20.0
  sharing_request_date: "19991104"
  sharing_request_percent: 26.6
  request_received_date: "19991129"
  sharing_request_type: "C"
  state_law_seized_asset_flag: false
  income_available_for_sharing: 9200.0
  sharing_type: "J"
  sharing_usa_expenses: 0.0
  equipment_purchase_use_flag: false
  official_use_flag: false
  other_use_flag: true
  salaries_use_flag: false
  vehicle_purchase_use_flag: false
  sharing_usms_expenses: 1258.6
  extraordinary_expenses_flag: false
  sub_object_classification_code: "4402"
  usms_lien_expenses_amount: 0.0
  sharing_execution_amount: 1193.28
  funds_location_code: "TFF"
  offset_or_payment_amount: 0.0
  budgetary_adjustment_percent: 0.0
  budgetary_adjustment_value: 0.0
}
equitable_sharing {
  asset_id: 1
  other_agency_ncic_code: "MDDOAHY00"
  update_timestamp: "2000-10-04-10.12.10.591000"
  approval_date: "20000811"
  foreign_asset_flag: false
  legal_counsel_certification_date: "20000811"
  legal_counsel_state: "DC"
  unique_assistance_flag: true
  contributed_hours: 377
  sharing_execution_date: "20000929"
  sharing_execution_status_code: "SO"
  federal_sharing_amount: 0.0
  investigative_agency_expense: 0.0
  information_origin_flag: true
  other_assets_flag: false
  outstanding_lien_amount: 0.0
  percent_to_share: 0.0
  sharing_request_date: "20000927"
  sharing_request_percent: 100.0
  request_received_date: "20000927"
  sharing_request_type: "C"
  state_law_seized_asset_flag: false
  income_available_for_sharing: 0.0
  sharing_type: "J"
  sharing_usa_expenses: 0.0
  equipment_purchase_use_flag: false
  official_use_flag: false
  other_use_flag: true
  salaries_use_flag: false
  vehicle_purchase_use_flag: false
  sharing_usms_expenses: 0.0
  extraordinary_expenses_flag: false
  usms_lien_expenses_amount: 0.0
  sharing_execution_amount: 0.0
  funds_location_code: "AFF"
  offset_or_payment_amount: 0.0
  budgetary_adjustment_percent: 0.0
  budgetary_adjustment_value: 0.0
}
